spring:
  datasource:
    url: ${INFOPLAY_DATABASE_URL}
    username: ${INFOPLAY_DATABASE_USERNAME}
    password: ${INFOPLAY_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

app:
  upload-folder:
    image-destination-folder: ${INFOPLAY_GAME_IMAGES_UPLOAD_FOLDER}
    game-destination-folder: ${INFOPLAY_GAME_ROMS_UPLOAD_FOLDER}
  retroarch:
    retroarch-run-command:
      - flatpak
      - run
      - org.libretro.RetroArch
